### ISSUE TITLE
Detect when a user made a rate

### ISSUE THREAD

**Issue by KhanMaytok** [wildfish/django-star-ratings#100]
Hi to everyone

I would like to detect when a user made a rating. I try with 

    $(document).on('click', '.star-ratings-rating-stars-container', function () {
         console.log('yassss');
    });

And other variants (with li, with ul, etc) But it doesn't works. Any ideas?

**Comment by OmegaDroid** [comment]
We hook our click handler up to `.star-ratings-rate-action` which may help.

I think it may be worth us adding an event into the rate request that fires on success/failure. I shall add a new story to add this functionality.

**Comment by KhanMaytok** [comment]
Great, it is resolved. Many thanks for the help
