### ISSUE TITLE
read_only hide starts

### ISSUE THREAD

**Issue by hishamkaram** [wildfish/django-star-ratings#102]
I want to show stars with `read_only` i.e rating average  represented by stars

**Comment by OmegaDroid** [comment]
Hi @hishamkaram, sorry for the late reply. We have just release version 0.5.5, can you let me know if you still see the issue.

**Comment by hishamkaram** [comment]
Solved

**Comment by subrush** [comment]
@hishamkaram
would you please tell how did you solve the issue. I have used the following in my index.html but didnot work
{{ templatetags read_only}}

**Comment by hishamkaram** [comment]
@subrush `read_only` not working so I decided to render the stars by myself in the template. take a look [here](https://github.com/wildfish/django-star-ratings/blob/83a79fbd4ce786eaa372d3f9325b26de1cd72980/star_ratings/templates/star_ratings/widget_base.html#L47)

**Comment by subrush** [comment]
thank you for your response
