### ISSUE TITLE
how can change language of texts ?

### ISSUE THREAD

**Issue by ghost** [wildfish/django-star-ratings#109]
hi , I'm trying to use this project but I need to translate some text like Average to Persian for example , what can I do for this ?

**Comment by OmegaDroid** [comment]
Hi @MrIllusion. Currently We don't support i18n properly (#22 addresses this). For now you will need to override the template. The templates you will be interested in are https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templates/star_ratings/widget.html and https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templates/star_ratings/widget_base.html.
