### ISSUE TITLE
How to use without templatetags

### ISSUE THREAD

**Issue by christianmtr** [wildfish/django-star-ratings#113]
I need to save ratings without templatetags (for design reasons), should be in the view with ajax post request. How I can do it?

**Comment by OmegaDroid** [comment]
You can post data to `/<ratings_root>/(?P<content_type_id>\d+)/(?P<object_id>\d+)/` to save your ratings.

The data should look like `{score: <value>}`.

**Comment by Mr-Phoebe** [comment]
I just wonder how can we get the score in our own views.py.
We need to store the records for rating.
