### ISSUE TITLE
Python object Overflow error. while loading {%rating object %}

### ISSUE THREAD

**Issue by nix1947** [wildfish/django-star-ratings#115]
Hello, I am working with django models where models has UUID as a primary keys. When I load django star templates, I got an overflow error. 
`{% ratings object %}`

OverflowError at /en/documents/legacy-of-leaders/detail/15db5415-d436-43ca-8bf9-917b6a1cb453/
Python int too large to convert to SQLite INTEGER
![overflowerror](https://user-images.githubusercontent.com/15655524/32943667-f7841c58-cbb4-11e7-9b9b-7753ac3b9fb4.png)

Is the `django star ratings` don't support uuid field as primary key ?

**Comment by OmegaDroid** [comment]
Hi @nix1947,

This is because the ratings model assumes the id to be an int. In general we would say keeping the id to an int is the best bet and treat the uuid as a slug on the model.

If this isn't an option we did some work for a previous issue that allows for the ratings model to be overridden. This is still experimental atm but if you want to try it out you can install the `feature/swapable-rating-model branch` and change the ratings model.

Information about setting up the custom model can be found here https://github.com/wildfish/django-star-ratings/tree/feature/swapable-rating-model#custom-rating-model.

**Comment by nix1947** [comment]
@OmegaDroid  Thanks, I will see it

**Comment by nix1947** [comment]
@OmegaDroid I install the features/swapable-rating-model branch and point to the custom model, But the changes are not reflected, I got the same error `Python int too large to convert to SQLite INTEGER`. 

I think `star ratings is not picking my custom model from my settings.py file` I don't know why, even  I verified by miswriting the model name, it didn't throw any error. 

Here is my custom model. simple as stated in docs. 
`import uuid
from django.db import models
from star_ratings.models import AbstractBaseRating

class MyRating(AbstractBaseRating):
    # By default django-star-ratings use  primary key as a positive integer field
    # Our model use UUID change object_id to UUID field.
    # See more info https://github.com/wildfish/django-star-ratings/tree/feature/swapable-rating-model
    # This model use django-star-rating feature/swapable branch.
    object_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
`
In settings.py file. 
`STAR_RATIGNGS_RATING_MODEL = 'ourrating.models.MyRating'`

**Comment by OmegaDroid** [comment]
Hi @nix1947, did fixing that typo (#116) sort your issue or is it still ignoring your model?

**Comment by nix1947** [comment]
@OmegaDroid Right now, I am able to use a custom model, but another thing I need to change the urls.py file to accept the UUID value. I have done that, and in the meantime, I got some JS error, while updating the rating. I will let you know,

**Comment by nix1947** [comment]
I implemented the fork version of this project by modifying the object_id field as UUID, thanks I am closing this issue

**Comment by venksj** [comment]
Hello @nix1947, I'm facing a similar issue in using the django-star-ratings package. 

I have a model where the primary key is a CharField. How do I use the custom model to make use of the ratings package with this?

thanks in advance!

**Comment by nix1947** [comment]
Use fork and change objid to be charged field

**Comment by OmegaDroid** [comment]
Hi guys, 

Just to let you know we just released 0.6.0 which includes the swapable ratings models to PyPI.

**Comment by nix1947** [comment]
Sounds good
