### ISSUE TITLE
Getting "ValueError: invalid literal for int() with base 10: 'COURSE00051'"

### ISSUE THREAD

**Issue by venksj** [wildfish/django-star-ratings#118]
Django: 1.11.7
python: 3.5.2
django-star-ratings: 0.5.6

In my models.py, I have a class called course which has a primary key of type CharField. 
The value "COURSE00051" is a primary key for one of the records that I want to display the rating for.

I want to use django-star-ratings with the course class to enable a user to provide a rating for the course.
However, it seems that the django-star-ratings works best with pk being an int field.

For my design, the pk cannot be an int. 

As suggested in an earlier issue, I looked at:
https://github.com/wildfish/django-star-ratings/tree/feature/swapable-rating-model#custom-rating-model

However, I'm not able to figure out the following:
* Do I need to create my own rating model by extending the AbstractBaseRating class? 
* IF yes, do I need to use object_id as a CharField?
* Also, what about the original course class that I have? Do I need to give a ForeignKey reference to that class within the new rating model class?

thanks in advance!

**Comment by OmegaDroid** [comment]
Hi @venksj, 

Yes you will need to create your own rating model with the `object_id` set to a `CharField`. There is an example of doing this [here](https://github.com/wildfish/django-star-ratings/tree/feature/swapable-rating-model#changing-the-pk-type-requires-django--110).

You shouldn't have to make any changes to to your course class.

One note is that you will need to install `django-star-ratings` from the github branch using `pip install git+git://github.com/wildfish/django-star-ratings.git@swapable-rating-model`. We are planning on doing an official release including this feature soon.

**Comment by venksj** [comment]
@OmegaDroid 

Thank you! I have dowloaded the new git branch and am working on your suggestions.

**Comment by venksj** [comment]
Thank you @OmegaDroid , it worked!! 

Steps:
1. Use the specific github branch:
      pip install git+git://github.com/wildfish/django-star-ratings.git@feature/swapable-rating-model
2. In settings.py, add 'star_ratings' to the INSTALLED_APPS
3. In urls.py, add a rule for star_ratings.
4. In myapp.models.py, extends the AbstractBaseRating class to add an object_id of the type that matches the primary key of your model. Let the name of new class be MyStarRating
5. In settings.py, set STAR_RATINGS_RATING_APP = "myapp.MyStarRating"
6. Now, add the {% load ratings %} to the template and continue with the rest of the stuff as per the documentation.
