### ISSUE TITLE
Average points is displayed via stars but I don't want it

### ISSUE THREAD

**Issue by summersonnn** [wildfish/django-star-ratings#120]
Hi. This may not be an issue, sorry if that's the case.

When the page loads, some of the stars are colorful and some of them are not. This reveals the average of the photo. As you can see below, I rated 7 but when the page loads 8,5 of 10 stars are full, that means average is 8.5
![untitled](https://user-images.githubusercontent.com/31991669/34445938-5c233e4c-ece8-11e7-89f6-c45ff959992c.jpg)

Another issue regarding that, when a user hovers on stars and then moves the cursor somewhere else, it rounds down to closest integer value. If we are to use the previous example, it rounds down to 8.

Is it possible to hide it all? I mean, making all of the stars full or all of them empty?

**Comment by zabbed** [comment]
I was able to get rid of the average and only fill the stars based on the user's rating.

First install `django-mathfilters`
Then add `'mathfilters'` to your `INSTALLED_APPS`

Then edit django-star-ratings/star_ratings/templates/star_ratings/widget_base.html:
Add `{% load mathfilters %}`

Change line 20 to `<div id="{{ id }}" class="star-ratings" data-max-rating="{{ star_count }}" data-avg-rating="{% if user_rating %}{{ user_rating.score }}{% else %}{{ 0 }}{% endif %}">`

Change line 39 to `<ul class="star-ratings-rating-foreground" style="width: {% if user_rating %}{{ user_rating.score|mul:100|div:star_count }}{% else %}{{ 0 }}{% endif %}%">`

Hope it works for you!

**Comment by summersonnn** [comment]
django-mathfilters is not supported for django-1.10.
That's why I'm getting "No module named mathfilters" error.

Any suggestions?

**Comment by OmegaDroid** [comment]
Hi @summersonnn,

Firstly, the hover issue where the stars are rounded down is definitely an issue and I'll take a look into it.

As for the hiding/showing I'm not sure what you are trying to do but if you want to show the user rating instead of the the average you can do this without any extra filter libraries. I would probably add the user percentage to the context and use that in the template. This may be a useful property to add to the user rating model.

**Comment by zabbed** [comment]
Ah, adding the user percentage property is a much better solution than my previous suggestion to use mathfilters.

I added this to the UserRating class in models.py:
```    
    @property
    def percentage(self):
        return (self.score / app_settings.STAR_RATINGS_RANGE) * 100
```
And changed line 39 in widget_base.html to:
`<ul class="star-ratings-rating-foreground" style="width: {% if user_rating %}{{ user_rating.percentage }}{% else %}{{ 0 }}{% endif %}%">`
