### ISSUE TITLE
500 Interval Error by uplading star.png

### ISSUE THREAD

**Issue by selvianl** [wildfish/django-star-ratings#121]
Hi all.

I used star-ratings for my project in local it was all fine. I just install with pip and I copied only css and js files to my static folder. It was working like a charm.

Then I carried my file to `pythonanywhere` to host and I am getting `500 HTTP Error` from star.png file. <br>My file structure is:

![image](https://user-images.githubusercontent.com/10786142/34461340-b96391a6-ee37-11e7-9b32-3e059b917192.png)

After Googling a bit the reason appeared as `wrong root directory` or `.htaccess`.  Here is my config in `pythonanywhere` :

![image](https://user-images.githubusercontent.com/10786142/34461310-ff34ef0a-ee36-11e7-82ab-98713c2ced8b.png)

One more thing. Being sudo in terminal is not allowed in `pythonanywhere` and I installed star-ratings by tapping `pip3.6 install --user django-star-ratings`. Additionally I didn't create any virtualenv.<br>Anyway, I checked again and I got `all requirments are satisfied massage`.  Additionally I checked from `site-packages` and everything was there.

**Comment by rolo** [comment]
Hi there. This looks to be something to do with how static files are set up on pythonanywhere. None of us have used pythonanywhere so I'm afraid I wouldn't know how to help with this.

This looks like it might be a good place to start -
 https://help.pythonanywhere.com/pages/DjangoStaticFiles/.
