### ISSUE TITLE
Hover rounding error

### ISSUE THREAD

**Issue by OmegaDroid** [wildfish/django-star-ratings#122]
After a user hovers over the stars and exits the highlighted stars are rounded down to the nearest int.

Originally reported in #120

**Comment by OmegaDroid** [comment]
@summersonnn I cant seem to reproduce this, what browser are you seeing this on?

**Comment by summersonnn** [comment]
After applying @zabbed 's solution which is changing the line 20 to

 "<div id="{{ id }}" class="star-ratings" data-max-rating="{{ star_count }}" data-avg-rating="{% if user_rating %}{{ user_rating.score }}{% else %}{{ 0 }}{% endif %}">"

it solved the problem of rounding down. Now when I hover and exit the stars, it highlights the stars according to my vote. This error no longer exists. The other is still there though.

**Comment by summersonnn** [comment]
After applying @zabbed 's solution which is changing the line 20 to

```
<div id="{{ id }}" class="star-ratings" data-max-rating="{{ star_count }}" data-avg-rating="{% if user_rating %}{{ user_rating.score }}{% else %}{{ 0 }}{% endif %}">
```

it solved the problem of rounding down. Now when I hover and exit the stars, it highlights the stars according to my vote. This error no longer exists. The other is still there though.
