### ISSUE TITLE
Is it possible to understand whether the object is rated or not in template without refreshing the page?

### ISSUE THREAD

**Issue by summersonnn** [wildfish/django-star-ratings#124]
Hi.
I want to hide the object in my template file when it's rated.
That's why I need to send the id of the object to a JS function when it's rated.

For example, in the following code, when the user clicks on the report button, the object is reported immediately. 

```
<form style="display: inline;" onclick="report('{{ photo.id }}', event)">
    <input class="btn btn-danger btn-lg" type="submit" value="Report" >
</form>
```

What I want is, when the user rates the object, pass the id of the object to a JS function to make it hidden without the need of a refresh. So, is it possible to check it in MY template? I know it is checked in widget_base.html.

**Comment by RabidCicada** [comment]
If all you want to do is hide it then you can simply use javascript to edit the div itself when they click it like:http://www.randomsnippets.com/2008/02/12/how-to-hide-and-show-your-div/

If you want actual understanding of the state of the object you'll need to expose an api on the server side or use the ones star_ratings provides, and perform a jquery/javascript get/post to retrieve and process real data when they user clicks.

**Comment by summersonnn** [comment]
@RabidCicada I will use JS once I know the id of the object to hide. Because there is a for loop and all the objects has the same div. I can not differentiate between them without knowing the id of the object.
Thanks though.

@OmegaDroid Okay, thanks.

**Comment by OmegaDroid** [comment]
I've just made a new release to add the js events (0.6.1). See https://github.com/wildfish/django-star-ratings#events
