### ISSUE TITLE
Custom Model Problem

### ISSUE THREAD

**Issue by RabidCicada** [wildfish/django-star-ratings#125]
**Description of Problem:**
I do a clean install with Django 2.0 etc.  I run makemigrations with custom model specified that uses UUID for object_id.  It fails by claiming my app isn't installed:(.  Previously I patched your code to allow UUID as the primary key since my models use UUID's as their primary key.  I figured I'd use the custom model approach since I saw you added it.  This happened in my own complex project but is easily reproducible on a simple as possible test app.

**How to Reproduce:**
django-admin startproject simple
cd simple
python manage.py startapp simpleapp
Edit settings.py INSTALLED_APPS to include star_ratings and simpleapp
```
'star_ratings',
'simpleapp'
````

Edit settings.py to add 
```
# Star Ratings settings
STAR_RATINGS_RATING_MODEL = 'simpleapp.CustomStarRating'
```

Edit simpleapp models.py to add
```
class CustomStarRating(AbstractBaseRating):
   object_id = models.UUIDField()
```

**Expected Results:**
It should properly allow my custom model.

**Actual Results:**
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/core/management/commands/makemigrations.py", line 159, in handle
    migration_name=self.migration_name,
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/db/migrations/autodetector.py", line 44, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/db/migrations/autodetector.py", line 128, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/db/migrations/state.py", line 214, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "/home/dev/rabidhire/tester/lib/python3.5/site-packages/django/db/migrations/state.py", line 278, in __init__
    raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field star_ratings.UserRating.rating was declared with a lazy reference to 'simpleapp.customstarrating', but app 'simpleapp' isn't installed.
```

**Pip freeze:**
```
pip freeze
amqp==2.2.2
asgi-redis==1.4.3
asgiref==1.1.2
asn1crypto==0.24.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
billiard==3.5.0.3
celery==4.2.0
celery-haystack==0.10
certifi==2018.1.18
cffi==1.11.4
channels==1.1.8
chardet==3.0.4
constantly==15.1.0
cryptography==2.1.4
cssselect==1.0.3
daphne==1.4.2
defusedxml==0.5.0
Django==2.0.1
django-allauth==0.34.0
django-appconf==1.0.2
django-bootstrap3==9.1.0
django-braces==1.12.0
django-celery-beat==1.1.0
django-cleanup==2.1.0
django-haystack==2.7.dev1
django-model-utils==3.1.1
django-pdb==0.6.1
django-star-ratings==0.6.0
django-widget-tweaks==1.4.1
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
kombu==4.1.0
lxml==4.1.1
msgpack-python==0.5.1
oauthlib==2.0.6
parsel==1.3.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
PyDispatcher==2.0.5
pyOpenSSL==17.5.0
pysolr==3.6.1.dev7+g52b8e0b
python-scrapyd-api==2.0.1
python3-openid==3.1.0
pytz==2017.3
queuelib==1.4.2
redis==2.10.6
requests==2.18.4
requests-oauthlib==0.8.0
Scrapy==1.5.0
scrapyd==1.2.0
scrapyd-client==1.1.0
selenium==3.8.1
service-identity==17.0.0
six==1.11.0
swapper==1.1.0
Twisted==17.9.0
txaio==2.8.2
urllib3==1.22
vine==1.1.4
w3lib==1.18.0
zope.interface==4.4.3
```

**Comment by RabidCicada** [comment]
[simple.tar.gz](https://github.com/wildfish/django-star-ratings/files/1664157/simple.tar.gz)

**Comment by OmegaDroid** [comment]
Hi @RabidCicada, I'm not sure of the correct solution to this but if I comment out the setting for the first time I call `makemigrations` the command then works as expected. I can also add the setting back in before running `migrate` and create further migrations after without issue.

I suspect this is an issue with how django builds it's dependency tree for migrations.

Could you try removing the setting before creating the initial migration and adding it back in before running the migrations and let me know how you get on while I keep looking into this.

**Comment by RabidCicada** [comment]
So that does solve it.  but seems like a nasty workaround.  Having to manually edit configs before/after makemigrations.

I know you may not be able to control that.  I feel like there must be a permanent solution somewhere.

**Comment by RabidCicada** [comment]
Alright...I didn't pay enough attention to your statement.  running migrate on star_ratings before anything else gets us in a sane state.  I was just doing makemigrations.

Probably should add a note to the docs:).

But also curious if you know a real fix.

Also slightly off topic...being able to use the new model feature is really great...but it still requires edits to star-ratings code because of the url path regex `url(r'(?P<content_type_id>\d+)/(?P<object_id>[a-z0-9]{32})/', Rate.as_view(), name='rate'),`

Be nice if that was modifiable in some easy manner

**Comment by OmegaDroid** [comment]
I've created #127 to address the pattern issue.

If there isn't a real solution to the migrations issue then we will just add something to the documentation but we'll see how that goes :).

**Comment by RabidCicada** [comment]
Ty sir!

**Comment by RabidCicada** [comment]
I have read further on this: wq/django-swappable-models#14 and https://github.com/wq/django-swappable-models.  It seems you don't need the 
```
swappable_dep = swapper.dependency('star_ratings', 'Rating')
if swappable_dep == migrations.swappable_dependency('star_ratings.Rating'):
    dependancies.append(swappable_dep)
```
Stuff unless you have a complicated hierarchy.  I'm about to try in my local env.  But just thought I'd pass reading along.

~Kyle

**Comment by RabidCicada** [comment]
I've spent a lot of time digging around.  It seems the only real solution is to have the settings file override commented out.  makemigrations for my own apps.  Then uncomment and migrate.

**Comment by OmegaDroid** [comment]
Yeah, I think we just need to add this to the documentation.

Thanks for your help

**Comment by skyler14** [comment]
So I tried creating this dummy custom model:

```
class MyRating(AbstractBaseRating):

	@property
	def zero(self):
		return 0;
```

then did makemigrations
`$ python manage.py makemigrations`

then put this in settings
`STAR_RATINGS_RATING_MODEL = 'main.MyRating'`

and I am still get the lazy reference error:
`ValueError: The field star_ratings.UserRating.rating was declared with a lazy reference to 'main.myrating', but app 'main' doesn't provide model 'myrating'.`

What am I doing wrong?

**Comment by OmegaDroid** [comment]
@skyler14 I'm not sure whats going on here, to clarify you are seeing this error when you run migrate?

Could you send an example showing the issue please?

**Comment by BoPeng** [comment]
@RabidCicada 

> So that does solve it. but seems like a nasty workaround. Having to manually edit configs before/after makemigrations.

I encountered the same problem and resolved it by
