### ISSUE TITLE
Provide method to programmatically rate objects

### ISSUE THREAD

**Issue by apaar97** [wildfish/django-star-ratings#132]
There should exist a method to rate object programmatically in view function or via AJAX requests

**Comment by apaar97** [comment]
This also addresses issue #56

**Comment by n3storm** [comment]
Why?

views.Rate has ajax option since at least 11 december.
And this how you programmatically rate an object (line 35)

`rating = self.model.objects.rate(self.get_object(), score, user=user, ip=ip)`

**Comment by apaar97** [comment]
I am sorry but I don't remember the exact problem I faced at that time. I wanted to integrate the rating models with DjangoRestFramework so that objects could be rated via REST API as well. There was some implementation issue, which unfortunately I cannot reproduce now. Eventually, there were some design changes in my project, so I forgot about this. Closing this issue for now.
