### ISSUE TITLE
 "django.core.context_processors.request"

### ISSUE THREAD

**Issue by omarkounda** [wildfish/django-star-ratings#135]
hi it seems like the exception raised haven't been updated to suit Django 2.0 requirement that have changed django.core.context_processors.request to django.template.context_processors.request'. 
exception is raising;

lib\site-packages\star_ratings\templatetags\ratings.py", line 20, in ratings
    raise Exception('Make sure you have "django.core.context_processors.request" in "TEMPLATE_CONTEXT_PROCESSORS"')
Exception: Make sure you have "django.core.context_processors.request" in "TEMPLATE_CONTEXT_PROCESSORS"

If anyone has a fix I will appreciate

**Comment by arkain** [comment]
I had to change from 
`render_to_response` to `return render(
            request` to resolve this
