### ISSUE TITLE
not working with turbolinks django

### ISSUE THREAD

**Issue by PHironaka** [wildfish/django-star-ratings#138]
I just finished implementing star ratings into my django app and turbolinks is preventing the ability to rate posts. It just clicks out to a dead link - example: ratings/17/24/?return=/post/post.id/

When I refresh the post page it works just fine.

I followed instructions from jquery turbolinks repo but still having the same issues.

Any tips would be appreciated.

**Comment by OmegaDroid** [comment]
Hi @PHironaka, I dont have any experience with turbolinks but it may be something to do with how it handles redirects. How are you making the ratings request? Are you using ajax?

Also if you are expecting the ratings request to redirect to a specific url you need to use `next` not `return` query string argument.

If this doesn't help, could you send a minimum example showing the issue.

Cheers

**Comment by OmegaDroid** [comment]
I think that the turbo links js is altering the behaviour of the links star ratings is also trying to also alter.

To get around this I have tried replacing the links with forms where we hijack the submit event (this has the added effect of the ratings working even if js is disabled).

Could you try installing the dsr version from feature/replace-links-with-forms please and let me know if that solves your issue?

Cheers

**Comment by PHironaka** [comment]
@OmegaDroid I'll give that a shot! Where can I find the dsr version?

**Comment by OmegaDroid** [comment]
You can install it by running 
```
pip install git+git://github.com/wildfish/django-star-ratings.git@feature/replace-links-with-forms -U
```

**Comment by PHironaka** [comment]
@OmegaDroid Do I need to be running on Django 2.07? My project is on 1.9.

**Comment by OmegaDroid** [comment]
1.9 should work fine

**Comment by PHironaka** [comment]
@OmegaDroid When I try installing the version you sent, it uninstalls version 1.9 and installs 2.0.7. I re installed 1.9 - still having the same issues on page load.

**Comment by OmegaDroid** [comment]
Try dropping the -U from the pip command. Could you create a simple example showing the issue please and tar it up?

**Comment by PHironaka** [comment]
@OmegaDroid Removed the -u, now when I try to rate a post I get the following error message:
Forbidden (403) CSRF verification failed. Request aborted.

I've attached the template star ratings is being used on

[court_detail.html.zip](https://github.com/wildfish/django-star-ratings/files/2167481/court_detail.html.zip)

**Comment by OmegaDroid** [comment]
I've added the csrf field, ca you try that please?

**Comment by PHironaka** [comment]
@OmegaDroid unfortunately, I'm still getting the same CSRF verification error after re-installing:

`pip install git+git://github.com/wildfish/django-star-ratings.git@feature/replace-links-with-forms`

**Comment by OmegaDroid** [comment]
pip may be behaving a little strangely upgrading the package, try uninstalling the previously installed version then install again

**Comment by PHironaka** [comment]
Hey @OmegaDroid sorry for the delay on my end. I gave this a shot and still having the same issues. Anything else I could try? If not I might just try disabling turbolinks on post detail views so it still functions as desired.

**Comment by OmegaDroid** [comment]
Are you still seeing the csrf issue? That seems odd since the csrf token should be present in the request now. It may be worth checking the request payload in your browser tools to check the data.

It may be that because of how turbo links is handling the requests that the two js libraries are just incompatible and turbo links needs to be disabled since the ratings widget requires the js to function correctly
