### ISSUE TITLE
Accessing raw data with django-star-ratings

### ISSUE THREAD

**Issue by ahmedsadman** [wildfish/django-star-ratings#139]
I am totally new in Django. I have created a blog project where one registered user can rate another registered user, using django-star-ratings library. For this, I have used default User model provided with Django, with another model UserProfile which holds extra info of the User object and is related by OneToOne relation.

Now, I can implement user rating in one of my templates, as given in the documentation. `{% ratings post.author %}`

Where `post.author` points to the User object.

1. I want to show the rating in also some other pages, in a raw form, suppose the User Dashboard page. Something like `user.rating.average` would do. How do I access the user's rating from the user object in the templates?

2. I want to sort the blog posts based on the rating of the authors, how do I do that? Note that every post contains a `author` field that is relates to the `User` object, and I want to sort blog posts based on the author's ratings. I know about the GenericRelation as shown in documentation. But the problem is, I want to sort by the author's rating, not the Post's rating itself, otherwise I could have just used GenericRealtion field in my Post model and get away with it. As the `User` object is already defined, I cannot find any way to modify it and add GenericRelation to it.

**Comment by OmegaDroid** [comment]
Hi @ahmedsadman,

Firstly I would suggest creating your own user model if you are at the start of a project. In my experience I often need to extend the user model (adding a `GenericRelation` is just one example) and this is much easier to do at the start of a project than later when the project is in production. In this case you could just use `user.rating.average` in your template and `order_by('author__rating__average')` in your query.

Assuming you can't create your own user model you could link your blog posts and ratings to a model you can control (ie the user profile). Failing this here's what I would do:

1. We don't currently supply a convenient way to get the ratings value in the template as such. Instead you could just pass the average rating to the template in the context. If this isn't possible then you could pass a custom template to the `{% ratings %}` template tag by doing something `{% rating object template=<custom_template> %}`, this will render the custom template passing a bunch of properties as the context (full list [here](https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templatetags/ratings.py#L40)), this includes `rating` which is the rating object for the object so you could include `{{ rating.average }}` in your custom template.

2. This can probably be done with sub queries, maybe querying all the user related ratings and getting a value list of the average rating with user id. You can then join this with the post (on user id) and sort by the rating average. The full docs for `SubQuery` is [here](https://docs.djangoproject.com/en/2.0/ref/models/expressions/#subquery-expressions). This may look something like this
```
ratings_sub = Rating.objects.filter(content_type=ContentType.objects.get_for_model(User), object_id=OuterRef('author_id'))
posts = Post.objects.annotate(author_rating=Subquery(newest.values('average')[:1])).order_by('author_rating')
```
