### ISSUE TITLE
Please Add documentation for 'how to use' django-star-ratings with needed screenshots

### ISSUE THREAD

**Issue by aloganat** [wildfish/django-star-ratings#140]
I am new learner of django and I wanted to use django-star-ratings to get reviews from user. I am not able to see the star icons in the html page. Could you please help me to solve this?

**Comment by OmegaDroid** [comment]
Hi @aloganat,

I'm not sure what you are having trouples with. Have you installed the app correctly and added the urls to the url conf as outlined in the documentation (here)[http://django-star-ratings.readthedocs.io/en/latest/?badge=latest#installation]?

Once you have done this you should be able to use the template tag by using ```
{% load ratings %}
<html>
...
{% ratings object %}
...
</html>
```
which is outlined (here)[http://django-star-ratings.readthedocs.io/en/latest/?badge=latest#usage].

Are you seeing any errors?

**Comment by aloganat** [comment]
Hi @OmegaDroid ,

Thanks for replying back quickly. Yes, I have added it, in the web page I am getting the following,

Average: 0
Rating Count: 0
You Rated: Not rated
Please log in to rate.

But,I dont want to login to rate. Directly, in the web page, I would like to see the star icons to rate the review.

**Comment by OmegaDroid** [comment]
In that case you need to enable [Anonymous Rating](http://django-star-ratings.readthedocs.io/en/latest/?badge=latest#anonymous-rating) and that should give you stars when not logged in.

**Comment by aloganat** [comment]
This is my models.py

from __future__ import unicode_literals
from django.db import models

# Create your models here.

from django.contrib.contenttypes.fields import GenericRelation
from star_ratings import get_star_ratings_rating_model_name

class RateTestimonial(models.Model):
    name = models.CharField(max_length=100)
    ratings = GenericRelation(get_star_ratings_rating_model_name(), related_query_name='ratetestimonial')

    def __str__(self):
        return self.name

This is my views.py

from django.shortcuts import render
from model_mommy import mommy
from .models import RateTestimonial
# Create your views here.
def testimonials(request):

    obj = RateTestimonial()
    context= {
        "obj": obj,
        "title": "List"
    }
    return render(request, 'testimonials.html', context)

Could you please let me whether am I using the django-star-ratings correctly?

**Comment by OmegaDroid** [comment]
That looks fine, to enable rating when you are not logged in set `STAR_RATINGS_ANONYMOUS = True` in the settings file.

**Comment by aloganat** [comment]
Thanks @OmegaDroid . I will try it by setting the option.

**Comment by aloganat** [comment]
Hi @OmegaDroid ,
I am getting the following error,
NoReverseMatch at /testimonials/
Reverse for 'rate' with arguments '(9, None)' not found. 1 pattern(s) tried: ['ratings/(?P<content_type_id>\\d+)/(?P<object_id>\\d+)/']

My App name is testimonials, I tried creating a newapp with 'ratings' name as well. But, still getting this error. Any idea how it can be solved?

**Comment by aloganat** [comment]
Hi @OmegaDroid ,
Could you please point me where I am going wrong?

**Comment by OmegaDroid** [comment]
This is an issue with the object you are passing to the ratings tag. The error message states it as found a url for rate but the required parameters are not met. In this case it requires 2 integers but you have passed 6 for the `content_type_id` and `None` for the `object_id`.

Without knowing how you are using the tag and what object you are passing to it i would guess you haven't saved the object yet, this would make the pk `None` which would mean it cant generate the correct url.

**Comment by aloganat** [comment]
This is my models.py
------------------------------
from future import unicode_literals
from django.db import models

from django.contrib.contenttypes.fields import GenericRelation
from star_ratings import get_star_ratings_rating_model_name

class RateTestimonial(models.Model):
name = models.CharField(max_length=100)
ratings = GenericRelation(get_star_ratings_rating_model_name(), related_query_name='ratetestimonial')

def __str__(self):
    return self.name
This is my views.py
---------------------------
from django.shortcuts import render
from model_mommy import mommy
from .models import RateTestimonial

def testimonials(request):

obj = RateTestimonial()
context= {
    "obj": obj,
    "title": "List"
}
return render(request, 'testimonials.html', context)


This is my html template file:
--------------------------------------

{% load ratings %}
{% load staticfiles %}
{% block content %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<div class='star-ratings star-ratings-rating-full star-ratings-rating-empty star-ratings-rating-foreground star-ratings-rating-stars-container'>
<h1> {{ title }} </h1>
    <p>{% ratings obj %}</p>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.js' %}"></script>
</div>
{% endblock %}

Could you refer me to any documentation/ working example that I can refer to pass the required  parameters. Could you please guide me how to fix this problem. 

Thanks in Advance!

**Comment by OmegaDroid** [comment]
The issue here is that the object hasn't been saved to the database and therefore you it hasn't been assigned a pk and therefore its passing `None` to the url which is not allowed.

You need to call `save` on your object before rendering the view eg:
```
obj = RateTestimonial()
obj.save()
context= {
"obj": obj,
"title": "List"
}
```

There is a full demo [here](https://github.com/wildfish/django-star-ratings/tree/develop/demo).

**Comment by aloganat** [comment]
Thanks a lot @OmegaDroid  for the help. I have tried the demo in my machine and its working fine.

**Comment by subrush** [comment]
Hi there i need help on the following
while i am testing the demo i was not able to get all list of object (only view 'foo bar baz'). i have checked before login and after loged in. where shall i do the modification. is it inside view.py  FooView class 
class FooView(DetailView):
    modelz = Foo
    def get_object(self, queryset=None):
        obj, created = self.model.objects.get_or_create(bar='foo bar baz')       
        return obj

**Comment by OAkala** [comment]
Hey, I just tried following the instructions for using this package and I noticed that the syntax for the url in url.py is not supported in django 2.xx. I tried to edit it as the following:
`path('ratings/', include('star_ratings.urls')),`
But now I am getting the following error:

> django.urls.exceptions.NoReverseMatch: 'ratings' is not a registered namespace

Please I need advice
