### ISSUE TITLE
how to relate this app with my model?

### ISSUE THREAD

**Issue by MidoCobra** [wildfish/django-star-ratings#141]
i dont know what to do with the views to relate this app with my models and templates .. 
actually i m totally lost and i always got errors !!
please i need a full documentation to explain everything ..
thanks

**Comment by OmegaDroid** [comment]
Hi @MidoCobra,

What errors are you seeing and how are you trying to use the app? Installing the app (with the urls) and including the template tag in your template (as stated in the documentation) should be enough to get this working.

**Comment by MidoCobra** [comment]
hi @OmegaDroid;
  well for example when i add {% ratings object %} in my template i get this error:

Exception Type: | TemplateSyntaxError
-- | --
Invalid block tag on line 29: 'static', expected 'endblock'. Did you forget to register or load this tag?

__________________________________
Then i replaced object with my models name Nothing happened !!
_______________________________
in details i have a Guide model in which it contains "name" field and i ve a separated users app in which i wanna them to add reviews and stars rating for that model .. 
and actually it is not clear at all for me what to replace instead of what .. 
and sometimes i thought that this app is not what i need .. it may be a istake from me .. actually i dont know ..
thanks for your help

**Comment by OmegaDroid** [comment]
The first error you are seeing is because you have not included the `static` library in your template, add `{% load static %}` to the top of your template (this is covered in our documentation).

To add rating to a specific object you add `{% rating object %}` to your template where `object` is an instance to a saved object in your database. By default, in the `DetailsView` from the standard django class based views this is called `object` in your template context but you need to replace `object` with whatever your object is called in your context.

**Comment by MidoCobra** [comment]
thanks for your support and thanks for your patience ..
now i m getting closer  .. i ve now my beautiful stars appear and user can just rate the guide and i can see the result of that in the admin site ..
now i dont know how to get the average ratings of many users to that guide .. and how to just let the user rate for one time ..
there is must be some code i use to know how to handle all of this in both my views and templates .. 
thanks again..
by the way i m new in all of that (i think it is clear enough :-) )
![capture](https://user-images.githubusercontent.com/35378010/42647069-1ed873ea-8603-11e8-96f3-dec961d665cc.JPG)

**Comment by MidoCobra** [comment]
and another problem ...
every time user rate a guide it creates a new instance in the guide model !! :-(

**Comment by OmegaDroid** [comment]
You can set `STAR_RATINGS_RERATE = False` (https://github.com/wildfish/django-star-ratings#settings) to stop rerating.

To get the ratings for objects in queries etc you can use the generic relationhip described [here](https://github.com/wildfish/django-star-ratings#ordering-by-ratings)

**Comment by MidoCobra** [comment]
OK i think im in the right way but now i published my site and suddenly the stars converted to dots and they cant appear .. but every thing else is ok ..
thanks and i ll not annoy you again .. (i hope not sure :-)  )

**Comment by MidoCobra** [comment]
update 
i tested the links of css and js , and they do nothing ..
i think they miss the right pass ..
cause i deleted both and nothing changed !
am i right ?
if so what shall i do ?

**Comment by OmegaDroid** [comment]
When you are deploying are you running `collectstatic` and serving your static directory somewhere? You may need to look at this https://docs.djangoproject.com/en/2.0/howto/static-files/deployment/#serving-static-files-in-production

**Comment by MidoCobra** [comment]
Done .. :-) 
one more thing how to edit the massage under the stars?
like : you rated .. etc ..
i dont want to hide it i just wanna edit the content..

**Comment by OmegaDroid** [comment]
To edit the content you can either create your own ratings rating template called `star_ratings/widget.html` or pass a template to the template tag using `{%ratings obj template=<my_template> %}`, the first whould be used if the change is site wide, the later for a one off change.

Your template should probably extend `star_ratings/widget_base.html` which can be found [here](https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templates/star_ratings/widget_base.html).

**Comment by MidoCobra** [comment]
well You thankfully approached many things to my mind .. and actually helped me too much, 
and i m sorry for my too much questions but i think that it is a manner commitment between programmers :-) .. and i really appreciate ...
so now i wanna ask about how to fill the stars in a read only mode , to just represent the users rate ..cause u know it is normal to add this beside the users review in the reviews list ..
thanks in advance ..
thanks for your patience 👍 ..

**Comment by OmegaDroid** [comment]
Glad you are making progress, you can pass a bunch of options to the tag one of which is `read_only`. The full list is [here] (https://github.com/wildfish/django-star-ratings/blob/develop/README.rst#template-tags)

**Comment by MidoCobra** [comment]
where i should type this please : 
icon_height: defaults to STAR_RATINGS_STAR_HEIGHT
icon_width: defaults to STAR_RATINGS_STAR_WIDTH
read_only: overrides the editable behaviour to make the widget read only
template_name: overrides the tempalte to use for the widget
...
i didnt got how to make the stars appears like read only ... !!

thanks ..

**Comment by MidoCobra** [comment]
it is not read_only as written in docs cause it didnt work..
so i tried {% ratings object read %}  ... it worked !

**Comment by MidoCobra** [comment]
but know i finally wanna override one more thing but i failed ..
= i have users that should be able to rate an object ..
now i want to show the rate of every user for every object .. 
can i ?
so i need it in stars or just in reading mode .. what ever works  i ll be satisfied .
thanks

**Comment by OmegaDroid** [comment]
What is `read`? The usage is `read_only=True`. You can replace `True` with a variable in your context if you need to change the behaviour based on the user.

This is the standard way to handle optional parameters in django template tags and I would suggest reviewing the custom template tags docs if you are unsure how this all works.

**Comment by MidoCobra** [comment]
i did it .. thanks ..

**Comment by MidoCobra** [comment]
Actually .. really appreciate .. and sorry cause i didnt saw your msg except now ..now i almost controlled everything in your app .. and i did it all what i need ..till now ..thanks for your effort .. but the idea was about weak documentations for beginners or may or intermediates too ...    On Thursday, September 13, 2018, 5:53:29 PM GMT+2, Daniel Bate <notifications@github.com> wrote:  
 
 
Closed #141.
