### ISSUE TITLE
Add support to s3 bucket

### ISSUE THREAD

**Issue by jlariza** [wildfish/django-star-ratings#142]
Good day,

I am using the library, but when I pushed to production I got an issue. I am using s3 and the library is not compatible with it. The library uses a relative path for the start image (/static/star-ratings/images/stars.png) but it does not work with s3.

Please, add support to s3 or add a workaround to avoid issues.

Thank you,

**Comment by jlariza** [comment]
Nevermind, I solved the issue adding the following line to my settings.py file

STAR_RATINGS_STAR_SPRITE = STATIC_URL + "star-ratings/images/stars.png"

**Comment by OmegaDroid** [comment]
Hi @jlariza, I'm going to reopen this as we should be using `static` to generate the sprite image location rather than just the setting which should fix the issue.
