### ISSUE TITLE
How can I rate only specific type of models that I want to rate

### ISSUE THREAD

**Issue by 00baker** [wildfish/django-star-ratings#146]
I have a big models.py file and I need to rate only specific models or specific fields. How can that be achieved?

**Comment by OmegaDroid** [comment]
Hi @00baker,

There is no mechanism for this, instead, if there is a model you don't want to be rated don't pass an object of that model to the ratings tag.

There is also no mechanism for rating specific fields other than making the field a foreign key and rating the related object.
