### ISSUE TITLE
'dict' object has no attribute '_meta'

### ISSUE THREAD

**Issue by soniamiah** [wildfish/django-star-ratings#160]
This is what I have in my models.py
class Rating(models.Model):
    recipe = models.IntegerField()
    rating = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.recipe

I want to rate the recipes. If I put {% ratings user %} it works but only once, I assume thats because it is rating the user or something but if I put {% ratings recipe %} I get 'dict' object has no attribute '_meta'. Please help!

**Comment by OmegaDroid** [comment]
Hi @soniamiah, yes `{% ratings user %}` is making a rating for the user and it only allows each user to make one rating unless `STAR_RATINGS_RERATE = True` in your `settings.py`.

for rating recipes you don't need to create you own rating model, the app is designed to use only one rating model for all models that has generic keys to your models.

You need to check what the recipe object is in your template context. The error suggests that its a dictionary and not a `Recipe` object which will not work.

**Comment by soniamiah** [comment]
How do you check that? This is my template and recipe where recipe is taken from an API call. 
{% extends 'blog/base.html' %}
{% load ratings %}
{% block content %}
<div class="title">
<h1>{{recipe.title}} </h1>
</div>
<div class="container-fluid ">
<img class="center" src="{{recipe.image}}"/>
<p>Rate recipe {% ratings recipe %}</p>

**Comment by OmegaDroid** [comment]
I would suggest debugging your view where you are generating the context and check what value `recipe` has or add `{{ recipe }}` to your template to render the full value

**Comment by soniamiah** [comment]
This is my view function:
def info (request):
    recipe= Recipes.info(str(id))
    return render(request,'blog/info.html', {'recipe': recipe})
And {{ recipe }} contains the json for my recipe description

**Comment by OmegaDroid** [comment]
Then that is your issue, the object passed to the `ratings` tag **MUST** be a django model object, you are passing it a dictionary.
