### ISSUE TITLE
Is there some possibility to hide description?

### ISSUE THREAD

**Issue by zurek11** [wildfish/django-star-ratings#163]
Is there some possibility how to hide these divs?:

- star-ratings-rating-average
- star-ratings-rating-value
- star-ratings-rating-count
- star-ratings-rating-user

Thanks.

**Comment by OmegaDroid** [comment]
You can completely change the widget template by overriding `star_ratings/widget.html` (https://github.com/wildfish/django-star-ratings#customize-widget-template)

**Comment by zurek11** [comment]
When I want to try that like this in my code:

![image](https://user-images.githubusercontent.com/18126979/55613837-ec6abe80-578b-11e9-891e-61c850737397.png)

It says:
![image](https://user-images.githubusercontent.com/18126979/55613876-03111580-578c-11e9-9b69-d2d75bca57c5.png)

Do you know why? Thanks.

**Comment by OmegaDroid** [comment]
You don't include the template inside your existing template, you need to create a new file in your templates directory called `star_ratings/widget.html`. You may want to take a look at the official docs for overriding a template https://docs.djangoproject.com/en/2.1/howto/overriding-templates/.

**Comment by EuclidesKinto** [comment]
hi, did you show specifically how you did it?
