### ISSUE TITLE
A csrf_token warning on using the ratings

### ISSUE THREAD

**Issue by erev0s** [wildfish/django-star-ratings#165]
first time tested and it is working great. Excellent work everyone!!!  
I am using the ratings for a model called `Books` following the tutorial [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website) using Django `2.2.2`. When i add the `{% ratings book %}` in my `book_detail.html` this warning is shown 
~~~~
/home/user/.local/lib/python3.6/site-packages/django/template/defaulttags.py:63: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
~~~~

My `view` for this is page is  
~~~~
class BookDetailView(generic.DetailView):
    model = Book

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            bookobj = get_object_or_404(Book, id=self.kwargs['pk'])
            context['fav'] = bookobj.favorited
        return context
~~~~

and the model where i also added the ratings
~~~~
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    ratings = GenericRelation(Rating, related_query_name='user_rating')
    favorited = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
~~~~

Any ideas on why this warning comes up?

**Comment by OmegaDroid** [comment]
Heya @erev0s, I think this has been fixed already but we haven't made a release from it. Could you try installing develop and let me know if the issue goes away using:

    pip uninstall django-star-ratings -y; pip install -e git+git@github.com:wildfish/django-star-ratings.git@develop#egg=django-star-ratings

**Comment by erev0s** [comment]
Indeed @OmegaDroid issue is fixed in the develop version!
Thank you for your answer

**Comment by OmegaDroid** [comment]
@erev0s FYI I've just deployed 0.8.0 so you can use a proper release rather than the github one
