### ISSUE TITLE
Another Custom Rating model problem

### ISSUE THREAD

**Issue by bnedwin** [wildfish/django-star-ratings#166]
Thank you very much for this awesome package, You make our developing life much easier.

While I was extending the AbstractBaseRating model to add a "reviews" field, I hit a bit of a snag. The stars display properly,  but when I try to rate the stars don't stick. I check my custom rating model in the Admin area and I see the rating, but I can't say the same for the templates. What could go wrong with doing this? Would you give us a detailed process toward achieving it? I see the link to the [Django docs](https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#substituting-a-custom-user-model), but if you could personalize it I think it would be better.

Here's my code: 

from django.db import (
    models,
)

from star_ratings.models import (
    AbstractBaseRating,
)
from django.utils.translation import (
    ugettext_lazy as _,
)
class EventRating(AbstractBaseRating):
    review = models.TextField(_('Reviews'))

**Comment by OmegaDroid** [comment]
Hi @bnedwin, I think the issue here is that you need to be swapping the user rating object not the base ratings object.

Sadly we don't currently support swapping the user rating model but we should probably add it here since it is supported elsewhere.
