### ISSUE TITLE
Problem with importing Rating from star_ratings.models

### ISSUE THREAD

**Issue by ezpher** [wildfish/django-star-ratings#167]
I was trying the following import: 

`from star_ratings.models import Rating`

and received an unresolved import error in VS Code. I followed the instructions in the readme almost exactly but removed the app_name from:

`url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),`

because that's unrecognised by django 2+

can someone please help?

**Comment by PeteSampras** [comment]
django2.x update: for those having this issue in the future, the solution was to just change that url() line to:
`path('ratings/', include('star_ratings.urls', namespace='ratings'), name='ratings'),`
