### ISSUE TITLE
make the widget read_only in permission check

### ISSUE THREAD

**Issue by erev0s** [wildfish/django-star-ratings#168]
upon creating specific permissions i would like only specific groups of users to be able to use the widget so i have the following lines in my template

~~~~
{% if perms.app_label.can_vote_stars %}
{% ratings object 16 16 widget.html %}
{% else %}
{% ratings object read_only=True 16 16 widget.html %}
{% endif %}
~~~~

This results in the following error 
~~~~
'ratings' received some positional argument(s) after some keyword argument(s)
~~~~

I tried to put the `read_only=True` to other positions as well but it did not work.
  
Any ideas?

**Comment by CrazyChief** [comment]
@erev0s Try to write like this:
`{% ratings object read_only=True icon_height=16 icon_width=16 template_name=widget.html %}`
or like this
`{% ratings object 16 16 True widget.html %}`
