### ISSUE TITLE
Cannot add or update a child row

### ISSUE THREAD

**Issue by CrazyChief** [wildfish/django-star-ratings#169]
Hi)
After providing a custom rating model, I still have problem with integration such as:
`django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails ('my_instance'.'star_ratings_userrating', CONSTRAINT 'star_ratings_userrat_rating_id_e7ac9370_fk_star_rati' FOREIGN KEY ('rating_id') REFERENCES 'star_ratings_rating' ('id'))')`

I think it depends on your implementation in star_ratings/\__\__init\__\__.py in get_star_ratings_rating_model_name and get_star_ratings_rating_model functions. Because UserRating model has relation only to Rating model in this case. Try to provide another implementation for it such as:
provide in app_settings.py
`@property
    def STAR_RATINGS_RATING_MODEL(self):
        return getattr(settings, 'STAR_RATINGS_RATING_MODEL', 'star_ratings.Rating')`

and update implementation for `get_star_ratings_rating_model_name` and `get_star_ratings_rating_model` functions like this:

`    def get_star_ratings_rating_model_name():
        parts = [x for x in app_settings.STAR_RATINGS_RATING_MODEL.split('.')]
        return swapper.get_model_name(parts[0], parts[1])`

`    def get_star_ratings_rating_model():
        parts = [x for x in app_settings.STAR_RATINGS_RATING_MODEL.split('.')]
        return swapper.load_model(parts[0], parts[1])`

I think it will help to avoid IntegrityError for db.

**Comment by jamesoutterside** [comment]
Hi @CrazyChief apologies for the late follow up, not able to reproduce this one so will close for now, if you have steps to recreate, drop them to us.
