### ISSUE TITLE
QueryInstance immutable // quote_from_bytes() expected bytes :Error+ possible solution

### ISSUE THREAD

**Issue by nicolai-schlemeier** [wildfish/django-star-ratings#170]
I had a rough start using the package.
Then the error "QueryInstance immutable" appeared.
It pointed to the post function in the "Rate" View. (views.py)
Dont know why, but it didnt want to touch:
data = request.POST or json.loads(request.body.decode())

I took care of that problem by deepcopying it:
from copy import deepcopy
...
            data_temp = request.POST or json.loads(request.body.decode())
            data = deepcopy(data_temp)

Then there was another error: "quote_from_bytes() expected bytes"
whicht had a problem with the redirect. I dont know why, but it made the return_url a list (len=1) instead of sting..
I corrected that by:
            return_url = return_url[0]

Now everything works fine, hopefully ;)
Hopefully i didnt destroy everything with those changes...

**Comment by willv** [comment]
What version of django were you running when you got this issue?

**Comment by nicolai-schlemeier** [comment]
I was using 2.2.4

**Comment by patroqueeet** [comment]
@nicolai-wachenschwan can you share why you closed this? have the same issue...

**Comment by nicolai-wachenschwan** [comment]
@patroqueeet Hey! I closed it, because I found a solution and shared it above.
I just hotfixed the upcoming errors, since I dont have enough experience to fix it properly.

**Comment by patroqueeet** [comment]
@willv can we reopen this as this is not yet fixed, and the code is truly wrong because `pop` in `QueryDict` will never work...

the fix will probably be either a `get()` or the mentioned `deepcopy` approach...
