### ISSUE TITLE
Is there a way to Call or Display name of Voters/Reviewers

### ISSUE THREAD

**Issue by josylad** [wildfish/django-star-ratings#171]
I can see that the usernames of those who have voted are being stored, but how do I call it to show it on the webpage? 
I want to have a list of the names of people who have reviewed a particular object. 
thanks in advance.

**Comment by jamesoutterside** [comment]
Hi @josylad Sorry for the late reply, for others who ask this, there are currently no built in tags/views for this other than in the admin panel, as they are likely to be fairly specific to you projects needs. 

By querying the UserRating model & you can display whatever you wish (view, template tag, DRF view etc). 

For example a very simply generic view without auth/permissions/pagination etc: 

```
# views.py
from django.views.generic.list import ListView

from star_ratings.models import UserRating


class UserRatingList(ListView):
    queryset = UserRating.objects.select_related('user')


# urls.py (after the standard ratings url)
path('ratings/users/', UserRatingList.as_view(), name='user-rating-list'),


# templates/star_ratings/userrating_list.html
<h1>Ratings by user</h1>
<ul>
{% for user_rating in object_list %}
    <li>{{ user_rating.user.username }} - {{ user_rating.score }}</li>
{% endfor %}
</ul>
```
