### ISSUE TITLE
Admin Panel Code Issues

### ISSUE THREAD

**Issue by trueman61** [wildfish/django-star-ratings#174]
Hi,

There is a problem in the admin panel. I'd appreciate it if you could help me.

Rating Average:
https://i.ibb.co/FwTrGy6/rating1.png

Score:
https://i.ibb.co/Xtc2n8s/rating2.png

**Comment by OmegaDroid** [comment]
release 0.9.1 should fix this

**Comment by trueman61** [comment]
Thank you so much.
