### ISSUE TITLE
Support Django 3

### ISSUE THREAD

**Issue by Sany07** [wildfish/django-star-ratings#175]
When i set install app i got this error

'' ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding ''

Python 3.8.0
Django==3.0

**Comment by rolo** [comment]
Hi Sany07. Apologies, this is a Django 3 compatibility issue. Leave this with me and I'll get a new version pushed with Django 3 support.

**Comment by Sany07** [comment]
Thank You :)

**Comment by PainKKKiller** [comment]
I use Django 3.0.3 and it works OK.
