### ISSUE TITLE
can i unregister in admin console ? 

### ISSUE THREAD

**Issue by nquang2448** [wildfish/django-star-ratings#180]
I have some problem. I try find the way to hide STAR_RATINGS models. But i dont know import what. 
![Screen Shot 2019-12-27 at 19 15 06](https://user-images.githubusercontent.com/44407463/71516776-67a56f00-28dd-11ea-8353-78e9d7a5f0a3.png)
sorry for my english. Thank you so much. Please help me :(

**Comment by nquang2448** [comment]
hello ? anyone help my please :(

**Comment by radiac** [comment]
Sorry for the delay. If you look in https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/admin.py you'll see we register the two models with the admin site at the end of the file.

You could change the permissions on those models so they're only visible in admin to superusers (using the standard django permissions framework)

Alternatively you can unregister them; in one of your own `admin.py` files, add:
```
from star_ratings import get_star_ratings_rating_model
from star_ratings.models import UserRating

admin.site.unregister(get_star_ratings_rating_model())
admin.site.unregister(UserRating)
```

(this will need to be run after star ratings has registered them, so it'll need to be an app after `star_ratings` in the `INSTALLED_APPS` list)
