### ISSUE TITLE
How to set language for this widget?

### ISSUE THREAD

**Issue by PainKKKiller** [wildfish/django-star-ratings#184]
May be my question sounds silly, I see trans tags, and locale folder, but I didn't find way to change language for this app.

**Comment by jamesoutterside** [comment]
Hi @PainKKKiller 

The language will adhere to [Django's translations](https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#how-django-discovers-language-preference), for example if you are wanting to use a single language changing [LANGUAGE_CODE](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-LANGUAGE_CODE) to one of the supported languages in the settings file for your project or the demo project. 

Thanks

**Comment by PainKKKiller** [comment]
Thanks for reply. It doesn't work for me. I checked all my locale settings I tried `translation.activate` in the view where this widget used, but I see only english language (and BTW my default language in settings isn't english). But anyway problem solved, I just extended template and translated this widget on my own. thanks for help.
