### ISSUE TITLE
clear form data/set existing rating to zero

### ISSUE THREAD

**Issue by rikachet1** [wildfish/django-star-ratings#191]
Hi,

I'd like to add a function where a user, who has already rated once, will click a "clear" button to set their rating form and score data back to 0. 

How would I go about doing this?

**Comment by rikachet1** [comment]
Similar to issue #75

**Comment by sebastianvdn** [comment]
Did you manage to find a way to do this?

**Comment by rolo** [comment]
Hiya. We've added this in https://github.com/wildfish/django-star-ratings/pull/194. You can use that branch for now and we'll make a release next week.
