### ISSUE TITLE
Customize widget template and Template Tags 

### ISSUE THREAD

**Issue by EuclidesKinto** [wildfish/django-star-ratings#193]
Customize widget?

app: books
model: book
Customize widget: books/template/book/star_ratings/rating_book.html

`{% extends "star_ratings/widget_base.html" %}`
`{% block rating_detail %}`
`???`
`{% endblock %}`
`
######
How to make?
#####
home.html

{% ratings book 13 13 template_name = rating_book.html %}

**Comment by 9mido** [comment]
You need to override templates. Make a project_name/templates/star_ratings/ folder with the widget.html file inside of it and then insert the code the documentation shows inside of widget.html. 

You might even also want to override widget_base.html by also placing it inside of project_name/templates/star_ratings/ folder.
