### ISSUE TITLE
Resquest

### ISSUE THREAD

**Issue by dera1992** [wildfish/django-star-ratings#196]
Please, how can i query the  users that rated a particular object? Thanks

**Comment by sebastianvdn** [comment]
`ratings = UserRating.objects.select_related('rating', 'user').filter(user=user)`

**Comment by sebastianvdn** [comment]
excuse me this is not right, you should do this: 
```
rating = Rating.objects.get(object_id=self.object.pk) # First get the rating for the object
user_ratings = rating.user_ratings.all() # This line gets you all the user ratings for your object
```

**Comment by dera1992** [comment]
Alright.Thanks very much.

**Comment by sebastianvdn** [comment]
If this solved you issue you can close it..
