### ISSUE TITLE
STAR_RATING_RATING_MODEL typo in documentation

### ISSUE THREAD

**Issue by mwikya** [wildfish/django-star-ratings#201]
hi, I think there is a typo in the documentation regarding STAR_RATINGS_RATING_MODEL settting. I was copying directly from the documentation as STAR_RATING_RATING_MODEL and things didn't work as I expected them to do.

**Comment by jamesoutterside** [comment]
Hi @mwikya, could you provide some details of the issue you encountered/exception and we can take a look into that, thanks.
