### ISSUE TITLE
admin stars not showing when using django admin with amazon s3

### ISSUE THREAD

**Issue by elyasha** [wildfish/django-star-ratings#208]
Requested URL: /static/star-ratings/images/admin_stars.png
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by elyasha** [comment]
I am willing to work at this issue, but please tell me if the project is always active ! ;)

**Comment by jamesoutterside** [comment]
Hi @elyasha 

Apologies for the delay in getting back to you, did you manage to make any progress with this or do you still need some assistance? If so could you drop a few more details about what you tried/your setup etc? 

Cheers
