### ISSUE TITLE
How to get the rating count and the the rating value for structured data (enriched search google)?

### ISSUE THREAD

**Issue by Umoja-Heshima** [wildfish/django-star-ratings#218]
Hi, I would like to integrate the rating value and the rating count of a page into the structured data of that page. How can I do this ? I tried this in my models.py :

```
from star_ratings.models import Rating

    @property
    def structured_data(self):
data = {
        	"@context": "https://schema.org/",
            "name": self.kichwa,
            "image": self.picha.url,
            'author': {
                '@type': 'Person',
                'name': self.mwandishi
            },
            "datePublished": self.tarehe_chapishwa,
            "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": Rating.average,
        "ratingCount": Rating.count,
      },

            }
```

However I get this error : Object of type DeferredAttribute is not JSON serializable

All is working fine without "AggregateRating".

So is there a way to integrate the ratingvalue and ratingcount of a page into its structured data ?

``

**Comment by jamesoutterside** [comment]
Hi @Umoja-Heshima 

Sorry for the delay in response. Hopefully you managed to resolve this, it looks like your accessing AggregateRating values via the class, you'd need to use self and access the rating from you model. 

Thanks 
James
