### ISSUE TITLE
Ratings not displaying correctly on iOS

### ISSUE THREAD

**Issue by richardblaine1974** [wildfish/django-star-ratings#228]
![star_ratings_iOS](https://user-images.githubusercontent.com/52042702/147828883-65af11c3-a142-4284-bd44-3a7f23bd0d85.jpg)

**Comment by richardblaine1974** [comment]
This is only failing on mobile safari. Please see the picture attached. Can anyone point me to the solution please? It works fine except on iPads and iPhones. Not getting very far using the web inspector on iPad to diagnose the issue. Any help would be appreciated!

**Comment by StuartMacKay** [comment]
Richard, I can create a similar effect if the foreground and background list items have different padding or margins. For example:
```
ul.star-ratings-rating-foreground li {
  margin-left: 8px;
}

ul.star-ratings-rating-background li {
  margin-left: 36px;
}
```
Since your screenshot shows the widget right-aligned and the default in the demo is left-aligned that extra styling information is being picked up by the list items?  Would it be possible for you to post any extra styling you applied and a snapshot of the HTML?

In the meantime I'll have a rummage around to see if I can find an iOS device so we recreate this exactly.

**Comment by richardblaine1974** [comment]
Hi Stuart, Thanks so much for looking into this!! 

So the html is here- 

> <div class="card mb-3" style="max-width: 1200px;">
    <div class="row no-gutters">
     <div class="col-md-4">
        
    </div>
    <div class="col-md-8">
        <div class="card-body">
            <div class="page-separator">
                <div class="page-separator__text bg-alt">{{ m.title }}</div>
            </div>
            <div class="row no-gutters">
                <div class="col-md-8">

                    <ul class="list-unstyled">
                      
                    </ul>
                </div>
                **<div class="col-md-4">
                <div class="col text-right">
                    {% ratings m 16 16 %} 
                </div>
                <div class="col text-right mt-4">
                 
                </div>
                </div>**
            </div>
        </div>
    </div>
</div>
</div> 

As you can see the only additional styling is in the bootstrap div classes wrapped around the ratings widget and everything is within a bootstrap card. 

I do have some inline css - temporarily - but it has no impact on the widget: 

> .card-img, .card-img-top {
border-top-left-radius: .5rem;
border-top-right-radius: 0 !important; 
}
.card-img, .card-img-bottom {
    border-bottom-left-radius: .5rem;
    border-bottom-right-radius: 0 !important; 
}
#id_lessons, #id_collections,#id_flashsubmit{
display: block;
list-style-type: none;
margin-block-start: 1em;
margin-block-end: 1em;
margin-inline-start: 0px;
margin-inline-end: 0px;
padding-inline-start: 40px;
}

I have seen no difference looking at the css rules applied in the web inspector when comparing safari on MacOS (all good) and the safari on iOS. I can improve the situation but I just don't see what safari mobile is doing differently to everything else so can't get it right! There must be something different so I will keep looking...

**Comment by richardblaine1974** [comment]
Hi Stuart - just wondering if you were able to look into this any further? I haven’t seen any difference in css styles being applied on iOS and macOS. Yet iOS produces the image above and MacOS does not.

**Comment by jdwpeterson** [comment]
Hi Richard,  not sure if you're still having trouble with this but i've found removing the padding from the `.star-ratings-rating-full` class fixed the issue e.g.

```
.star-ratings-rating-full, .star-ratings-rating-empty {
  display: block;
  background: url("/static/star-ratings/images/stars.png") no-repeat;
  border: 0;
  padding: 0;
}
```

Please let me know if this works for you too.

**Comment by richardblaine1974** [comment]
Amazing!!! Thanks so much!! Worked like a charm. Fantastic.
