### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Solanar** [wildfish/django-star-ratings#49]
I get the following error after running `pip install django-star-ratings`:

`WindowsError: [Error 206] The filename or extension is too long: 'c:\\users\\<user>\\appdata\\local\\temp\\pip-1omakv-build\\star_ratings/static/star-ratings/js/node_modules/browserify/node_modules/crypto-browserify/node_modules/public-encrypt/node_modules/parse-asn1/node_modules/asn1.js/node_modules/minimalistic-assert/'`

There are a number of folders/files that are too long.

**Comment by fuzzpedal** [comment]
Hi Solanar,
I've applied a fix which I've tested on Windows. We are planning another release soon, but until then you can install using:
`pip install git+https://github.com/wildfish/django-star-ratings.git`

Thanks
