### ISSUE TITLE
Problem with Js "onmouseenter" with different star icon size?

### ISSUE THREAD

**Issue by gustavklopp** [wildfish/django-star-ratings#52]
I've tried it on Firefox and Chrome:
******************
![screenshot from 2015-11-06 08 48 51](https://cloud.githubusercontent.com/assets/6438275/10992242/8742d2b6-8464-11e5-8292-0b76686329d2.png)
******************
![screenshot from 2015-11-06 08 50 40](https://cloud.githubusercontent.com/assets/6438275/10992244/8b6c9ab6-8464-11e5-99e9-a4180b769981.png)
******************
![screenshot from 2015-11-06 08 51 06](https://cloud.githubusercontent.com/assets/6438275/10992246/8d4cc720-8464-11e5-9e2c-2ea865304f6d.png)
******************
![screenshot from 2015-11-06 08 51 26](https://cloud.githubusercontent.com/assets/6438275/10992247/8f33cd9a-8464-11e5-82c3-75debb772822.png)
******************

As you see:
When the user has not rated yet: The mouse over highlights the star wrongly with one more star on the right.
But the rating is good and fits where the mouse has clicked.

When the user has rated, if he mouses over again on the stars, the mouse over is right...

No problem if I use the original size of 32x32 (here, it's 16x16)

**Comment by rolo** [comment]
Should be fixed on master now. Please test with:

`pip install git+https://github.com/wildfish/django-star-ratings.git`

And let us know if any probs. Thanks for reporting.

**Comment by gustavklopp** [comment]
It works great! Thanks for you work!
