### ISSUE TITLE
Display "rating average" on other pages

### ISSUE THREAD

**Issue by gustavklopp** [wildfish/django-star-ratings#57]
I'm trying to display the star staring on other webpage (in addition to the page where the user can actually vote and change the rating).

My model is:
```
class Article(models.Model):
   ...
    rate = GenericRelation(Rating, related_query_name='articles')
```
Then, I'm trying to get the rating average for my object `article`  in my template with:
`{{ article.rate.average }}`

I've tried also:
`{{ article.rate.rating.average }}` 

But the field is still blank. How can I access some fields inside the ratings models? Thanks a lot in advance!

**Comment by rolo** [comment]
It's via a related manager, so the syntax is a little awkward. You'd have to use:

    {{ article.ratings.get.average }}

I can see that this isn't really intuitive, so we have an issue open already to make this nicer for the next release (#57).

Hope that helps - let me know if you have any other probs.

**Comment by gustavklopp** [comment]
Thanks, it's working great!
In the same time, I've found another solution, inspired from : http://stackoverflow.com/questions/4641981/how-can-i-traverse-a-reverse-generic-relation-in-a-django-template

```
{% for element in article.rate.all %}
{{ element.average }}
{% endfor %}
```

But yours is more straightforward obviously!
