### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by miljevic** [wildfish/django-star-ratings#58]
When I type: pip install django-star-ratings, I get:
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-build-8_ynw5yv\\django-star-ratings\\star_ratings/static/star-ratings/js/node_modules/browserify/node_modules/crypto-browserify/node_modules/public-encrypt/node_modules/parse-asn1/node_modules/asn1.js/rfc/2560/test

**Comment by rolo** [comment]
Hiya. Could I ask you to please try again now? Let me know what happens. Thanks!

**Comment by miljevic** [comment]
It installed successfully now. Thanks.

**Comment by rolo** [comment]
Brilliant :)
