### ISSUE TITLE
[SOLVED] 'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by alzearafat** [wildfish/django-star-ratings#61]
Hi,

First, thank you for such a great work! I really need your plugin :)

But I have one issue with it. I'm sure I already following your instruction step-by-step, but still no good, please have a look :

Screenshot : 
![error](http://i67.tinypic.com/t7bz8p.jpg)

This is my log : 
 ```
"GET /accounts/zea/ HTTP/1.1" 500 187315
```
Did I miss something here? Maybe I should modified my models's too?

I'm using Django 1.8.7

Thank you in advance for any help you can provide :)

**EDIT**

SOLVED!

I change ratings object, to ratings profile (since my models is profile) on template
Thank you

**Comment by rlburb** [comment]
I'm having this same problem but can't get it to work. Are you saying you changed it the "ratings profile" because your models are in your profile app? or because your template is in or profile app? Or neither and I am just misunderstanding completely?

**Comment by fuzzpedal** [comment]
`{% ratings profile %}` was used because the object available to the template was called `profile` rather than `object`.
Elsewhere alzearafat was using `profile.get_mugshot_url` for example.

**Comment by radamizell** [comment]
So if I have a model called Post, i should be using {% ratings Post %}, but how should I modify my Post model to add a ratings field?

**Comment by rolo** [comment]
The template tags needs to know the name of the object in your template context. Your model may be called `Post` but it can be passed into the template as anything, it might be called `object` (which is the default for a generic view) or it might be called something else you've specified.

**Comment by radamizell** [comment]
Ahh I see. You've helped to find the weak spot in my knowledge, I'm going to do some research on how templates work and be back at it. Thanks so much!

**Comment by imsaiful** [comment]
I have the same problem. What should I do? I have 5 Indian news channel and want to enable rating by user.
