### ISSUE TITLE
After start rate click, screen goes blank

### ISSUE THREAD

**Issue by sunjoomoon** [wildfish/django-star-ratings#66]
All seem to be fine, but after I click the star rating, the browser goes blank - nothing shown. But in the browser url there looks like below

```
domain.com/ratings/82/26/?return=/zh-hans/tut3/cook/26/
```

And nothing happens...

What am I missing ?

**Comment by jonashagstedt** [comment]
Could you give us some more details:
*  Browser used
*  JavaScript enabled?
*  Python version etc.

I am guessing you've replaced your current website domain with *domain.com*?

**Comment by jonashagstedt** [comment]
@sunjoomoon Is this still an issue?
