### ISSUE TITLE
how can I import?

### ISSUE THREAD

**Issue by emilopez** [wildfish/django-star-ratings#67]
I am trying to add  the field to my model, but, I didn't find the correct way to import. 

when i try

ratings = GenericRelation(Rating, related_query_name='foos')

obviously receive  a "NameError: name 'Rating' is not defined".
But I cant find any doc to do the correct import.

Really thanks.

**Comment by jonashagstedt** [comment]
Try: `from star_ratings.models import Rating`

**Comment by radiac** [comment]
That looks like it should work - I've added it to the docs.

**Comment by emilopez** [comment]
Greats! 
Finally I have discovered looking the example.
Thanks!
