### ISSUE TITLE
Remove the info under the stars

### ISSUE THREAD

**Issue by emilopez** [wildfish/django-star-ratings#69]
Dears, 

I would like remove all the info messages under the stars (Average, Rating Count, You Rated, Please log in to rate), because I have two django views. One view is about an abstract, and the other a more detailed. At the first I need show only the five stars.

Can I do that?

really thanks

**Comment by jonashagstedt** [comment]
If you create a new template `star_ratings/widget.html` (under your template directory).

And add this code:

```{% extends "star_ratings/widget_base.html" %}

{% block rating_detail %}
{% endblock rating_detail %}
```

Then all the messages should no longer be visible.
You can see the entire template here:
https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templates/star_ratings/widget_base.html#L51

Saludos

**Comment by emilopez** [comment]
Thanks Jonas, I tried that and it worked perfectly. But, I would like to re-enable all the messages again in an other detailed view. Could you help me, please?  

Thanks in advance.

**Comment by radiac** [comment]
A quick way would be to use CSS to hide the elements you don't want, ie

    .star-ratings-rating-average, .star-ratings-rating-count, .star-ratings-rating-user {
        display: none;
    }

See https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templates/star_ratings/widget_base.html#L50 to figure out which elements to hide.

Another approach would be to change the template tag to accept a `template` variable to override the default template path - you could then customise the template each time you used the tag. I'll look at doing that at some point in the next couple of weeks, but we'd welcome a PR if you get to it before me.

**Comment by jonashagstedt** [comment]
CSS sounds like the simplest choice here.
Just wrap the ratings in a container with a class

```
<style>
.hide-rating-info .star-ratings-rating-average { display: none; }
</style>
<div{% if not show_rating_info %} class="hide-rating-info"{% endif %}>
    ... rating template tag etc. here
</div>
```

**Comment by jonashagstedt** [comment]
@emilopez is this still an issue?

**Comment by emilopez** [comment]
no, it's ready. thanks

**Comment by crazeoni** [comment]
do i need to reconstruct the whole star-ratings app?
