### ISSUE TITLE
Can't display stars by themselves.  Can't access the average ratings as integers in order to use the data.

### ISSUE THREAD

**Issue by Zackazt** [wildfish/django-star-ratings#79]
###### 1. Say I wanted to take all of the average ratings of articles by a particular user, and give them an average rating based off of that?  This may already be possible after digging into source code for a bit, however that may be an important feature to include right out of the box with documentation.

---
###### 2. I think there should be a way for us to access each part of the rating display as well individually.  For instance on the preview, you may want to only show the stars, and not the rest of the details about the ratings.

---

**Comment by Zackazt** [comment]
Say I wanted to take all of the average ratings of a particular category, and create an average rating of of that?

**Comment by OmegaDroid** [comment]
Hi @Zackazt,

1. It seems like this can be done using django querysets. Something like ```Blog.filter(user=target_user).aggregate(avg_rating=Avg('rating__average'))``` should do the trick. I don't think we will want to add anything to the app for this as it will be too dependent on the users implementation
2. You can change which template is used by creating a template at `star_ratings/widget.html`. Take a look at https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/templates/star_ratings/widget_base.html for the base template. This will be a site wide change however, I've added #88 to fix this.
3. I've created #89 for this
