### ISSUE TITLE
using Django CSRF

### ISSUE THREAD

**Issue by rootraid** [wildfish/django-star-ratings#81]
I've been having issues with CSRF on Django1.9 (Forbidden CSRF token missing or incorrect.): /ratings/... 

What would be the best way to securely submit a rating using the Django CSRF?

**Comment by OmegaDroid** [comment]
The default js automatically hooks up adding the csrf token to the post request. Are you using the default js by including something like `<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.js' %}"></script>`?
