### ISSUE TITLE
invalid literal for int() with base 10: 'Eid Offer at Amari Dhaka'

### ISSUE THREAD

**Issue by azmainamin** [wildfish/django-star-ratings#83]
Hello.
In my template, I have a for loop that goes over 'deals' with each instance labelled as 'deal'. Therefore, I put {% ratings deal %}. Then I get this error: invalid literal for int() with base 10: 'Eid Offer at Amari Dhaka'

I see that its trying to convert the title of the deal to a rating. How do i solve this? Thank you.

**Comment by jonashagstedt** [comment]
It looks like you are just getting the title / name of the deal.

If you change `{% ratings deal %}` to `{{ deal.pk }}` does it output the primary key of the deal?

**Comment by azmainamin** [comment]
I figured it out. The problem was that my title was my pk. I changed it to have a different pk.
