### ISSUE TITLE
Cannot rate: Please log in to rate.

### ISSUE THREAD

**Issue by azmainamin** [wildfish/django-star-ratings#84]
Does nothing when I touch on the stars. Shows this under the ratings: 'Please log in to rate.' My web app does not have any 'user'. Its open for all. How can I enable any one to rate?

**Comment by azmainamin** [comment]
Can someone help me with this?

**Comment by azmainamin** [comment]
@jonashagstedt Hey man, I would really appreciate your help. My app is stuck because of this.

**Comment by jonashagstedt** [comment]
We have a PR pending here: https://github.com/wildfish/django-star-ratings/pull/82 
I haven't reviewed this PR and it's not passing all checks but from the description it should allow anonymous users to rate.

**Comment by azmainamin** [comment]
Thank you. Any idea when you might look at that pr?  Also, can I start
using that pr right away? Thanks again.

**Comment by jonashagstedt** [comment]
You can use that PR now, simply pip install from Github. 

I am currently in a car driving across Europe so I am not sure when I (or anyone from Wildfish) will have time for that, but if you try it out please let me know if you find any issues as that will speed up the review of it.

**Comment by azmainamin** [comment]
Thank you. I will test it and let you know. Have a safe trip.

**Comment by OmegaDroid** [comment]
This functionality was added in 0.5.3

**Comment by azmainamin** [comment]
Thank you so much!
