### ISSUE TITLE
Users cannot vote again

### ISSUE THREAD

**Issue by SanderLy** [wildfish/django-star-ratings#90]
Django version: 1.10.1
Python: 2.7
Browser: UC Browser and Google Chrome.

STAR_RATINGS_RERATE = True

Problem: User can give a rating if the object being rated (i.e. book) is not yet in the userRating and Rating models. The problem is that whenever I try to reload the page and rerate again in the console it says matching query does not exists.

![image](https://cloud.githubusercontent.com/assets/11423702/19386444/d213601c-9246-11e6-85e5-be01712de69a.png)

Also when I opened the developer tools I saw errors whenever I try to rerate the book

![image](https://cloud.githubusercontent.com/assets/11423702/19386466/f308ff70-9246-11e6-8a04-9ba2383db998.png)

![image](https://cloud.githubusercontent.com/assets/11423702/19387022/39aa610a-924a-11e6-826b-1454892b90a1.png)

What seem to be the problem? I have followed the installation steps properly

**Comment by OmegaDroid** [comment]
Hi @SanderLy,

I've tried running an example locally using python 2.7 and all is working fine.

I notice that your return url is `/book/0316376736` where as the ratings url uses `316376736`. I wonder if we are assuming the id is a number and dropping the leading 0. 

Could you try sending the rating data to `/ratings/9/0316376736/` using something like postman please and let me know if that works?

Cheers.

**Comment by OmegaDroid** [comment]
In fact I have just tried it and this seems to be the issue. I will take a look at a fix for it.

**Comment by OmegaDroid** [comment]
Ok, I've created an experimental branch `feature/swapable-rating-model`. This allows you to create your own Rating model and swap out the default one. You should be able to do something like this:

```
class MyRating(AbstractBaseRating):
    foo = models.TextField()
```

And set `STAR_RATINGS_RATING_MODEL` in your settings file (similar to how django handle swappable user models).

You will also need to rerun the migrations. 

Let me know how you get on.

**Comment by SanderLy** [comment]
I appreciate the quick reply. I have extended the AbstractBaseRating. Also, I have setup the object_id to to a charField. Where should the user rating data be saved, in the rating model that I created or the default Star Ratings model?

Also, I'm still getting the same errors. Should I also do a form for this model and register this to the admin.py?

Sorry for the trouble but I just started learning django.

**Comment by OmegaDroid** [comment]
It sounds like you haven't set the model in your `settings.py`. You need to set the `STAR_RATINGS_RATING_MODEL` setting. This should be something like:

```
STAR_RATING_RATING_MODEL = '<app_name>.<model_name>
```

Once you have done this all the forms and the admin should use your model instead of the default `Rating` model. Take a look at how django handles the user model because this works in basically tha same way (https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#substituting-a-custom-user-model)

**Comment by OmegaDroid** [comment]
You could also try changing your model if that's possible, it often makes sense to let django create its own primary key by not setting one yourself. You could then use your id as a separate unique field.

**Comment by SanderLy** [comment]
It's okay now. I already fixed it. I followed your advice by letting django create the primary key then by extending the AbstractBaseRating model created my custom model. 

Thanks for the help and the great django app.

**Comment by OmegaDroid** [comment]
Ok great. One last thing, if you are letting django create the primary key then you probably don't need to specify your own model. There's no harm leaving it in and it will make it easier if you want to modify it in the future but that's up to you.

Good luck :+1:
