### ISSUE TITLE
IP address from request.META.get('REMOTE_ADDR') issue

### ISSUE THREAD

**Issue by delneg** [wildfish/django-star-ratings#94]
I came accross this error:
    **DataError at /ratings/18/3/ invalid input syntax for type inet: "b''"**

After googling and i found the problem:
ip = self.request.META.get('REMOTE_ADDR') - this line in views.py gets the ip **only** from **REMOTE_ADDR**, however it should get it also from **HTTP_X_REAL_IP**, as described in [http://stackoverflow.com/questions/34238623/invalid-input-syntax-for-type-inet-db-error-in-django-app-with-postgres-and-gu](Stackoverflow)
Please look into this.
I will provide full logs/configs if needed, the setup is Django 1.10.3, Python 3.5.2, nginx 1.10.0, Postgresql 9.5

**Comment by bee-keeper** [comment]
Hi,

Thanks for the report!  I've fixed this in the commit below but will leave open until this gets merged to master and another release gets rolled. 

https://github.com/wildfish/django-star-ratings/commit/51c4206723cdcee00f322b62e150436450ccc2d1

**Comment by delneg** [comment]
The solution seems to work, added it to my requirements file as a commit
