### ISSUE TITLE
STAR_RATINGS_RERATE = False does not work

### ISSUE THREAD

**Issue by jcmoon** [wildfish/django-star-ratings#95]
I'm having problem with the rerate.
I set STAR_RATINGS_RERATE=False and STAR_RATINGS_ANONYMOUS = True, but it still let me rerate the object as anonymous.
I'm not sure if log in user will work because my website does not need user log in.
I'm new to python and Django, not sure where I did wrong, any help is appreciated!

**Comment by OmegaDroid** [comment]
Hi @jcmoon,

I don't think these 2 settings are compatible as we don't store anything client side for identification. If you want to use `STAR_RATINGS_RERATE=False` you will need to use `STAR_RATINGS_ANONYMOUS=True`. 

We could add in a cookie to identify the user when they rate something but this isn't really a solution as the user can just clear it and be able to rate again.
