### ISSUE TITLE
Different ratings on same page?

### ISSUE THREAD

**Issue by ghost** [wildfish/django-star-ratings#97]
I'm not sure if this is the correct place to ask, but is there any way to have ratings from multiple different users on the same page?

**Comment by keenanfinn** [comment]
I am struggling with this issue. Is there a way to loop through the ratings for each user?

**Comment by OmegaDroid** [comment]
Hi guys, you should be able to access a users rating using the related name using something like:

```
ratings = user.userrating_set.all()
```
