### ISSUE TITLE
Can't get model to show in template

### ISSUE THREAD

**Issue by radamizell** [wildfish/django-star-ratings#99]
New to Django, feel like I'm close to figuring out where I'm going wrong here. I am getting the same `'str' object has no attribute 'meta' `error as a previous issue, but have been trying to pass the context to my template to no avail. In models have: 
```
class Rate(models.Model):
        name = models.CharField(max_length = 140)
	ratings =  GenericRelation(Rating, related_query_name= 'object_list')


	def __str__(self):
		return self.id
```

And in views, 
```
def RateList(request):
	queryset = Rate.objects.filter(ratings__isnull=False).order_by('ratings__average')
	context= {
		"object_list": queryset,
		"title": "List"
	}
	return render(request, 'UploadApp/upload.html', context)
```
and lastly, in my template I've put `{% ratings object_list %}` into the html. Not sure if I'm just overlooking some small detail?

**Comment by OmegaDroid** [comment]
Hi @radamizell, the `ratings` tag only works on rated objects not their querysets so you will need to do something like 

```
{% for obj in objects_list %}
    {% ratings obj %}
{% endfor %}
```

**Comment by radamizell** [comment]
Hi, thank you for responding. I tried putting the for loop into my template, but I'm just getting a blank template back(no error message though!). Forgive me if it's a dumb question, but I'm not seeing a rating field in my admin under  my "Rate" model.  Only the  name field is there, so I added a few objects with names. There is a separate rating object in the admin, so I'm not sure how that would connect to the Rate object, which I'm trying to sort like shown in the docs. Ultimately, I'm just trying to create a list of objects that can be rated and sorted by rating.

**Comment by radamizell** [comment]
I think something may be clicking, do I need to create two separate models, one to pass ratings to the existing ratings models that exist in admin, and another to pas the queryset and sort?

**Comment by radiac** [comment]
Hi @radamizell! Your current model is fine, you just need to sort out how to pass objects into your template.

In your view you are passing a queryset (list of objects) into your template on a template variable called `object_list`. Your template can then access the queryset on that variable name and loop through the objects, showing the details for that object. So if you remove the `s` from OmegaDroid's answer, you should be able to loop through all the objects in your queryset, eg:

```
{% for obj in object_list %}
    <p>{{ obj.name}}: {% ratings obj %}</p>
{% endfor %}
```

The template won't give you an error if the variable doesn't exist - that's a feature of django's templates.

For your admin problem, are you sure you've got your ratings field in the admin fields? Do you want to paste your admin class so we can see what you're talking about?

**Comment by radamizell** [comment]
Thanks for the reply! I tried the for loop the way you described, still no luck. When I inspect the element I see the div that I'm trying to put it in, but it doesn't display anything. Here's what my template looks like:
```
{% extends "Wallapp/header.html" %}
{% load ratings %}
{% block content %}
<div>
{% for obj in object_list %}
    <p>{{ obj.name}}: {% ratings obj %}</p>
{% endfor %}
</div>
{% endblock %}
```
As far as the admin goes, I think I'm just seeing the star ratings model that came with the app. Its an entirely different model than the "Rate " model that I created. When I go to add a new "Rate" object, no ratings field appears, just the name field. I was told that the "GenericRelation"  function that I got from the doc would do that

**Comment by radamizell** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24996714/22779296/26b84216-ee88-11e6-9c0d-535cdee52a2a.png)

![untitled22](https://cloud.githubusercontent.com/assets/24996714/22779348/6b472afa-ee88-11e6-9a22-adb3fa9afd9b.png)


and thats what i see in admin

**Comment by radiac** [comment]
In that case it sounds like your queryset is empty? There are neater ways to debug, but put a print statement in your view to see what the queryset contains:
```
def RateList(request):
	queryset = Rate.objects.filter(ratings__isnull=False).order_by('ratings__average')
	print('Queryset:{}:'.format(queryset))
	context= {
		"object_list": queryset,
		"title": "List"
	}
	return render(request, 'UploadApp/upload.html', context)```

and you should get something printed at the console (assuming you're using runserver). If you're using python 2 rather than python 3 you'll need to remove the brackets around the print statement.

**Comment by radamizell** [comment]
Ok, I think I'm starting to understand how the app works. So I've got my Rate model, which I have updated to be a simple object with only a _name_ field:  
```
from star_ratings.models import Rating
class Rate(models.Model):
	name = models.CharField(max_length = 140)
	def __str__(self):
		return self.name
```

my view, which I'm setting the queryset to include _all() _ objects now, and the context is set to _object_list_ :


```
from UploadApp.models import Rate

def RateList(request):
	queryset = Rate.objects.all()
	context= {
		"object_list": queryset,
		"title": "List"
	}
	return render(request, 'UploadApp/upload.html', context)
```
and finally using a for loop to tie the the _object_list_ context object to {% ratings object %} in the template:

```
{% extends "Wallapp/header.html" %}
{% load ratings %}


{% block content %}
<ul>
{% for obj in object_list %}
    <p>{% ratings obj %}</p>
{% endfor %}
</ul>
{% endblock %}
```
for some reason, even after making migrations, I'm still getting an empty <div> in my template (even though I've created a few "Rate " objects with 'name ' fields)? BTW I can't thank you guys enough for the help, this community is awesome.

**Comment by radamizell** [comment]
Also, I noticed the star rating static js and css files arent in my static folder for my app, should they be there? I thought the pip install and migrate would have taken care of those static files?
